### ISSUE TITLE
Can HDF5Array persist the dimnames too?

### ISSUE THREAD

**Issue by phaverty** [Bioconductor/HDF5Array#13]
That sure would be cool. Storing the dimnames separate from the data causes disasters occasionally :-)

**Comment by hpages** [comment]
I've been making some good progress on this. Should be ready soon...

**Comment by phaverty** [comment]
Awesome, Herve, not having to worry about mismatched data and metadata will help me sleep much better! Thanks!

**Comment by hpages** [comment]
Done in HDF5Array 1.15.12 (see commit c2cd0268).

Cheers!
