### ISSUE TITLE
Warning: no function found corresponding to methods exports from 'HDF5Array' for: 'write_sparse_block'

### ISSUE THREAD

**Issue by DustinSokolowski** [Bioconductor/HDF5Array#43]
Hey!

Thank you for your great package! I, along with many others, rely on your package for ours to function and it has made a world of difference.

I have been trying to update my package on CRAN for the last month or so and I've been unable to due to the following warning: 
"Warning: no function found corresponding to methods exports from 'HDF5Array' for: 'write_sparse_block'".

After googling that warning, I have noticed that about a half dozen other packages have been unable to update within the last week or so for the same reason. 

I was wondering if you had any insight onto what this warning could mean? Perhaps you have removed that function and a package that I depend on that uses your package (e.g., Seurat) is relying on an older version?

Thanks so much!
Dustin

**Comment by hpages** [comment]
Hi,

The `write_sparse_block()` method was removed from **HDF5Array** a while ago (in June 2020, see commit https://github.com/Bioconductor/HDF5Array/commit/9ebb3f8796f141d7a63565ea6b22076c3c5b3cb8) so it seems to me that your package is trying to import something that no longer exists in recent versions of **HDF5Array**.

The general recommendation is that, when you work on your package, and before you send it to CRAN, you need to make sure that you're using the current version of R (4.0) and Bioconductor (3.12), and that all your packages are up-to-date. You can check this with `BiocManager::valid()`. The current stable version of **HDF5Array** is 1.18.1. That's what you should have if you're using the current BioC release (BioC 3.12). Also make sure to run `R CMD INSTALL <pkg_dir>` + `R CMD build <pkg_dir>` + `R CMD check --cran <pkg_src_tarball>`: this should catch any problem.

Best,
H.

**Comment by DustinSokolowski** [comment]
Hey!

Thank you for taking the time to explain what I should have probably already known so clearly.  I don't have any more warnings and my package and I are better for it.

Thanks again!
Dustin
