### ISSUE TITLE
Object '.replace_dir' not found

### ISSUE THREAD

**Issue by BBBBunnyZ** [Bioconductor/HDF5Array#51]
I came up with this error when calling 'HDF5Array' in bsseq.
Here is the source code from bsseq::read.bismark.
>>>
    if (!dir.exists(dir)) {
      HDF5Array:::.create_dir(dir)
    }
    else {
      HDF5Array:::.replace_dir(dir, replace)
    }
But when I run bsseq it shows this error:
>>>
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object '.replace_dir' not found

And it not just happened in '.replace_dir', but also happened in '.create_dir'.
So I think maybe the problem is because the HDF5Array package was not successfully imported.
But when I use library(HDF5Array), there is no error at all.
So I'm wondering where the problem is.
Thank you so much!

**Comment by hpages** [comment]
Please provide a reproducible example and your `sessionInfo()`.

You're very likely mixing packages from different Bioconductor releases (e.g. an old **bsseq** with a recent **HDF5Array**), which is _always_ a bad idea. This is why Bioconductor users should _always_ install packages with `BiocManager::install()`, to avoid that problem. You should be able to fix your installation with `BiocManager::install()`.

**Comment by hpages** [comment]
Were you able to sort this out @BBBBunnyZ ?
